name: 💬 Feedback on Course Material
description: Submit feedback on a specific part or file in the IKEA Camunda training material.
title: "[Feedback] "
labels: ["feedback", "course"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🙏 **Thank you for reviewing the IKEA Camunda training material!**
        This form is for **one specific comment or piece of feedback**.  
        Please submit a new issue for each separate comment you want to make.  
        Be as clear as possible, and reference the exact **file or step** you are commenting on.

  - type: input
    id: file
    attributes:
      label: Which file or step does your feedback relate to?
      description: Provide the exact filename or step number if possible.
      placeholder: "part-03-exception-handling/final/thumbnails-production.py"
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: What is your feedback?
      description: Describe what you found unclear, incorrect, missing, or worth improving.
      placeholder: "The instructions in this file were hard to follow because..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this important?
      description: Help us understand why the issue matters—does it block learning, cause confusion, etc.?
      placeholder: "Because without this clarification, I couldn't complete the task..."
    validations:
      required: false

  - type: input
    id: time_spent
    attributes:
      label: How long did it take you to work through this part?
      placeholder: "Approximate time in minutes"
    validations:
      required: false

  - type: textarea
    id: suggestions
    attributes:
      label: Optional suggestions?
      placeholder: "You could consider rewording the example or adding a screenshot..."
    validations:
      required: false