name: 💬 Feedback on Course Material
description: Submit feedback on a specific part or file in the IKEA Camunda training material.
title: "[Feedback] "
labels: ["feedback"]

body:
  - type: markdown
    attributes:
      value: |
        🙏 **Thank you for reviewing the IKEA Camunda training material!**
        This form is for **one specific comment or piece of feedback**.  
        Please submit a new issue for each separate comment you want to make.  
        Be as clear as possible, and reference the exact **file or step** you are commenting on.

  - type: input
    id: file
    attributes:
      label: Which file or step does your feedback relate to?
      description: Provide the exact filename or step number if possible.
      placeholder: "part-03-exception-handling/final/thumbnails-production.py"
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: What is your feedback?
      description: Describe what you found unclear, incorrect, missing, or worth improving.
      placeholder: "The instructions in this file were hard to follow because..."
    validations:
      required: true